services:
  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      VITE_REACT_APP_API_URL: "http://10.0.19.19:8000/mern-be"


networks:
  mern_network:
    driver: bridge

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally

